import type {NextPage}  from 'next'
import { useSession , signOut} from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { CustomNextPage } from '../types/CustomNextPage'

const Home:CustomNextPage = () => {
  const{ data, status } = useSession();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      {data?.user?.name || <Link href='/auth/signin'>Go To SignIn</Link> }
      {status === 'authenticated' && <button onClick={()=>signOut()}>Sign Out</button>}
      <Link href='/catagories' style={{margin: "1rem"}}>Protected Page</Link>
      </main>

      
    </div>
  );
};

Home.requireAuth = true;

export default Home;